### ISSUE TITLE
Changing Shared Service VPC CIDR

### ISSUE THREAD

**Issue by vennemp** [bdwyertech/aws-landing-zone-initiation#3]
I am attempting to change the CIDR of the Shared Service VPC and am getting an error.  I edited the aws-landig-zone-shared-service-vpc.json file in the parameters/core-accounts folder and uploaded it back into the S3 bucket (making sure to use the appropriate KMS key) and am getting the following error

```
    ret = method(value, rule, path) 
  File "/codebuild/output/src065391350/src/validation/custom_validation.py", line 16, in account_validation 
    raise AssertionError(msg) 
AssertionError: Missing Email address for Account: logging 
Manifest file failed schema validation 
 
[Container] 2019/06/19 13:56:17 Command did not exit successfully bash $current/validation/run-validation.sh $ARTIFACT_BUCKET exit status 1 
[Container] 2019/06/19 13:56:17 Phase complete: BUILD State: FAILED 
[Container] 2019/06/19 13:56:17 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: bash $current/validation/run-validation.sh $ARTIFACT_BUCKET. Reason: exit status 1 
```

But there is not "logging" account in the manifest.yaml file - it is referred to as "log-archive"...

**Comment by vennemp** [comment]
Please note I did not change this.. this was the default value..

**Comment by bdwyertech** [comment]
This isn't the place for this, I'd open a case with your TAM.
